---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: akka-deployment
  annotations:
    security.alpha.kubernetes.io/sysctls: net.core.somaxconn=262144
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: akka-http
    spec: 
      containers:
      - name: akka-http-max-connections
        image: sebastianharko/akka-http-max-connections:0.1
        imagePullPolicy: Always
        env:
        - name: MAX_CONNECTIONS
          value: "10240"
        - name: BACKLOG
          value: "1000"
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5
            memory: 5Gi
          limits:
            cpu: 5
            memory: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: akka
spec:
  selector:
    app: akka-http
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
