---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: web
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: twopc
        image: sebastianharko/2pc:6.9
        imagePullPolicy: Always
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5
            memory: 5Gi
          limits:
            cpu: 5
            memory: 5Gi
---
kind: Service
apiVersion: v1
metadata:
  name: akka
spec:
  selector:
    app: http
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
