---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: golang-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: golang-http
    spec:
      containers:
      - name: golang-ping-pong
        image: sebastianharko/golang-ping-pong:1.0
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 5
            memory: 4Gi
          limits:
            cpu: 5
            memory: 4Gi
---
kind: Service
apiVersion: v1
metadata:
  name: golang
spec:
  selector:
    app: golang-http
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
  loadBalancerSourceRanges:
    - 0.0.0.0/0
